- hosts: all 
  become: yes
  vars:
    nix_user: "wfaler"
    dotfiles_repo: "https://github.com/wfaler/dotfiles.git"  
    dotfiles_dir: "/home/{{ nix_user }}/dotfiles"
    nix_zsh_path: "/home/{{ nix_user }}/.nix-profile/bin/zsh"
    alacritty_repo: "https://github.com/alacritty/alacritty.git"
    alacritty_dir: "/home/{{ nix_user }}/dev/alacritty"
    user_home: "/home/{{ nix_user }}"
    docker_arch: "amd64"
    tasks:
    ## start Apt and Debian/Ubuntu/PopOS specific install
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Consider the cache valid for 1 hour
    - name: Install apt dependencies
      apt:
        name: 
          - autoconf 
          - build-essential 
          - patch
          - libssl-dev
          - libyaml-dev
          - stow
          - clang
          - xclip
          - libreadline6-dev
          - zlib1g-dev
          - libgmp-dev
          - libncurses5-dev
          - libffi-dev
          - libgdbm6
          - uuid-dev
          - libfontconfig-dev
          - cifs-utils
          - fontconfig 
          - libfontconfig-dev
          - wireguard
          - wireguard-tools
          - curl
          - git
          - xz-utils
          - ca-certificates
        state: present
    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Create dev directory
      become_user: "{{nix_user}}"
      file:
        path: "{{user_home}}/dev"
        state: directory
        mode: '0755'

    - name: Download and store the Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Dearmor GPG key
      ansible.builtin.shell: gpg --dearmor < /tmp/docker.gpg > /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ docker_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      apt:
        update_cache: yes          
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: present
    # end Apt stuff and Debian/Ubuntu/PopOS specific install
    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Add nix_user to docker group
      user:
       name: "{{ nix_user }}"
       groups: docker
       append: yes
    - name: Create .envrc file
      become_user: "{{ nix_user }}"
      file:
        path: "{{ user_home }}/.envrc.fish"
        state: touch
        modification_time: preserve
        access_time: preserve
    - name: Create .config directory
      become_user: "{{ nix_user }}"
      file:
        path: "{{ user_home }}/.config"
        state: directory
        mode: '0755'
    - name: Clone dotfiles repository
      become_user: "{{ nix_user }}"
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        version: main  
        update: no 
      register: git_clone
    - name: Run stow in dotfiles directory
      become_user: "{{ nix_user }}"
      command: stow .
      args:
        chdir: "{{ dotfiles_dir }}"
      when: git_clone.changed 
 
